[workspace]
members = [
    "sudachi",
    "sudachi-cli",
    "sudachi-fuzz",
    "sudachi-wasm",
    "sudachi-napi",
    "plugin/input_text/*",
    "plugin/oov/*",
    "plugin/path_rewrite/*",
    "python"
]

default-members = [
    "sudachi",
    "sudachi-cli"
]
