[package]
name = "sudachi-napi"
version = "1.0.0-pre.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
sudachi = { path = "../sudachi" }
napi = "2"
napi-derive = "2"

[build-dependencies]
napi-build = "1"
