name: napi
"on":
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "7.12.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"
      - run: pnpm -C sudachi-napi i --frozen-lockfile
      # caching https://github.com/docker/build-push-action/blob/48888e0b1305dca3a741ceb3b5a04ea336cd2626/docs/advanced/export-docker.md
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          # same configuration as docker-compose.yml
          tags: sudachi-napi-build
          file: sudachi-napi/Dockerfile
          load: true
      - run: npm -C sudachi-napi run build
      - run: npm -C sudachi-wasm/packages/cli run build # download dictionary
      - run: npm -C sudachi-napi run test
